### ISSUE TITLE
Write a contract that allows delegating ENS tokens selectively to delegates.

### ISSUE THREAD

**Issue by makoto** [ensdomains/governance-contracts#13]

**Comment by caliburn886** [comment]
final message


i just want say to whom ever response about about the fake character because i really don't know who is responsible about that so i will talk in general to whoever involved and have nothing than respect to the other's.
first of all if you were think that you wanna bother me or attack my reputation i really feel sorry for you just because the time and power that you spend without having a great result like you was expecting to have .
second ,,, you can see how long time i was ignore this game because that's isn't my style to play such a dishonor game ,,, it will be just a waste of time ,, not to talk also about the financial effect and you know exactly how much money you locked and how much i loss because of of that and because i wasn't able to move my nft but the good part is that the codes is my witness,,
 
so my response will be legally through the court because i sure if didn't they will be a more moves or games and i don't see a better way to stop this,,,  in the end i wish after  the investigation they just find a bug or a various that was cousin the situation 


> 

i
